name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build with Poetry
        run: poetry build

      - name: Setup Poetry stuff 👀
        run: poetry config repositories.test https://test.pypi.org/legacy/

      - name: Publish package to TestPyPI
        run: poetry publish --username wdsrocha --password ${{ secrets.test_pypi_password }} --repository test
